// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_defines/diabolique_module_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto {
  static const uint32_t offsets[];
};
class socket_passthrough_init;
struct socket_passthrough_initDefaultTypeInternal;
extern socket_passthrough_initDefaultTypeInternal _socket_passthrough_init_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::socket_passthrough_init* Arena::CreateMaybeMessage<::socket_passthrough_init>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class socket_passthrough_init final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:socket_passthrough_init) */ {
 public:
  inline socket_passthrough_init() : socket_passthrough_init(nullptr) {}
  ~socket_passthrough_init() override;
  explicit PROTOBUF_CONSTEXPR socket_passthrough_init(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  socket_passthrough_init(const socket_passthrough_init& from);
  socket_passthrough_init(socket_passthrough_init&& from) noexcept
    : socket_passthrough_init() {
    *this = ::std::move(from);
  }

  inline socket_passthrough_init& operator=(const socket_passthrough_init& from) {
    CopyFrom(from);
    return *this;
  }
  inline socket_passthrough_init& operator=(socket_passthrough_init&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const socket_passthrough_init& default_instance() {
    return *internal_default_instance();
  }
  static inline const socket_passthrough_init* internal_default_instance() {
    return reinterpret_cast<const socket_passthrough_init*>(
               &_socket_passthrough_init_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(socket_passthrough_init& a, socket_passthrough_init& b) {
    a.Swap(&b);
  }
  inline void Swap(socket_passthrough_init* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(socket_passthrough_init* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  socket_passthrough_init* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<socket_passthrough_init>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const socket_passthrough_init& from);
  void MergeFrom(const socket_passthrough_init& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(socket_passthrough_init* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "socket_passthrough_init";
  }
  protected:
  explicit socket_passthrough_init(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
    kIpv6FieldNumber = 3,
    kServerFieldNumber = 4,
  };
  // required string ip = 1;
  bool has_ip() const;
  private:
  bool _internal_has_ip() const;
  public:
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // required string port = 2;
  bool has_port() const;
  private:
  bool _internal_has_port() const;
  public:
  void clear_port();
  const std::string& port() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_port(ArgT0&& arg0, ArgT... args);
  std::string* mutable_port();
  PROTOBUF_NODISCARD std::string* release_port();
  void set_allocated_port(std::string* port);
  private:
  const std::string& _internal_port() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_port(const std::string& value);
  std::string* _internal_mutable_port();
  public:

  // required bool ipv6 = 3;
  bool has_ipv6() const;
  private:
  bool _internal_has_ipv6() const;
  public:
  void clear_ipv6();
  bool ipv6() const;
  void set_ipv6(bool value);
  private:
  bool _internal_ipv6() const;
  void _internal_set_ipv6(bool value);
  public:

  // required bool server = 4;
  bool has_server() const;
  private:
  bool _internal_has_server() const;
  public:
  void clear_server();
  bool server() const;
  void set_server(bool value);
  private:
  bool _internal_server() const;
  void _internal_set_server(bool value);
  public:

  // @@protoc_insertion_point(class_scope:socket_passthrough_init)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr port_;
    bool ipv6_;
    bool server_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// socket_passthrough_init

// required string ip = 1;
inline bool socket_passthrough_init::_internal_has_ip() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool socket_passthrough_init::has_ip() const {
  return _internal_has_ip();
}
inline void socket_passthrough_init::clear_ip() {
  _impl_.ip_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& socket_passthrough_init::ip() const {
  // @@protoc_insertion_point(field_get:socket_passthrough_init.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void socket_passthrough_init::set_ip(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:socket_passthrough_init.ip)
}
inline std::string* socket_passthrough_init::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:socket_passthrough_init.ip)
  return _s;
}
inline const std::string& socket_passthrough_init::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void socket_passthrough_init::_internal_set_ip(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* socket_passthrough_init::_internal_mutable_ip() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* socket_passthrough_init::release_ip() {
  // @@protoc_insertion_point(field_release:socket_passthrough_init.ip)
  if (!_internal_has_ip()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ip_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ip_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void socket_passthrough_init::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:socket_passthrough_init.ip)
}

// required string port = 2;
inline bool socket_passthrough_init::_internal_has_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool socket_passthrough_init::has_port() const {
  return _internal_has_port();
}
inline void socket_passthrough_init::clear_port() {
  _impl_.port_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& socket_passthrough_init::port() const {
  // @@protoc_insertion_point(field_get:socket_passthrough_init.port)
  return _internal_port();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void socket_passthrough_init::set_port(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.port_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:socket_passthrough_init.port)
}
inline std::string* socket_passthrough_init::mutable_port() {
  std::string* _s = _internal_mutable_port();
  // @@protoc_insertion_point(field_mutable:socket_passthrough_init.port)
  return _s;
}
inline const std::string& socket_passthrough_init::_internal_port() const {
  return _impl_.port_.Get();
}
inline void socket_passthrough_init::_internal_set_port(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.port_.Set(value, GetArenaForAllocation());
}
inline std::string* socket_passthrough_init::_internal_mutable_port() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.port_.Mutable(GetArenaForAllocation());
}
inline std::string* socket_passthrough_init::release_port() {
  // @@protoc_insertion_point(field_release:socket_passthrough_init.port)
  if (!_internal_has_port()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.port_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.port_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void socket_passthrough_init::set_allocated_port(std::string* port) {
  if (port != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.port_.SetAllocated(port, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.port_.IsDefault()) {
    _impl_.port_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:socket_passthrough_init.port)
}

// required bool ipv6 = 3;
inline bool socket_passthrough_init::_internal_has_ipv6() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool socket_passthrough_init::has_ipv6() const {
  return _internal_has_ipv6();
}
inline void socket_passthrough_init::clear_ipv6() {
  _impl_.ipv6_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool socket_passthrough_init::_internal_ipv6() const {
  return _impl_.ipv6_;
}
inline bool socket_passthrough_init::ipv6() const {
  // @@protoc_insertion_point(field_get:socket_passthrough_init.ipv6)
  return _internal_ipv6();
}
inline void socket_passthrough_init::_internal_set_ipv6(bool value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.ipv6_ = value;
}
inline void socket_passthrough_init::set_ipv6(bool value) {
  _internal_set_ipv6(value);
  // @@protoc_insertion_point(field_set:socket_passthrough_init.ipv6)
}

// required bool server = 4;
inline bool socket_passthrough_init::_internal_has_server() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool socket_passthrough_init::has_server() const {
  return _internal_has_server();
}
inline void socket_passthrough_init::clear_server() {
  _impl_.server_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool socket_passthrough_init::_internal_server() const {
  return _impl_.server_;
}
inline bool socket_passthrough_init::server() const {
  // @@protoc_insertion_point(field_get:socket_passthrough_init.server)
  return _internal_server();
}
inline void socket_passthrough_init::_internal_set_server(bool value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.server_ = value;
}
inline void socket_passthrough_init::set_server(bool value) {
  _internal_set_server(value);
  // @@protoc_insertion_point(field_set:socket_passthrough_init.server)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_5fdefines_2fdiabolique_5fmodule_5fmessages_2eproto
